# Generated by Django 3.0.6 on 2020-05-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=255)),
                ('ccode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=10, verbose_name='Route Name')),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='To', to='routes.City')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From', to='routes.City')),
                ('through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.City')),
            ],
        ),
    ]
