# Generated by Django 3.0.6 on 2020-05-14 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterField(
            model_name='city',
            name='ccode',
            field=models.CharField(max_length=5, verbose_name='City Code'),
        ),
        migrations.AlterField(
            model_name='city',
            name='cname',
            field=models.CharField(max_length=255, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='From', to='routes.City'),
        ),
    ]
